type: "diff_drive_controller/DiffDriveController"

left_wheel: "left_wheel_to_base"
right_wheel: "right_wheel_to_base"

pose_covariance_diagonal:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
